version: "3.9"
services:
  eth-explorer:
    image: "node:14.18.3"
    container_name: eth-explorer
    working_dir: /usr/src/app
    ports:
      - "8002:8000"
    command: bash -c "npm start"
    volumes:
      - .:/usr/src/app
    restart: always
